### PR TITLE
Add support for "Loading any service with `dinit` on `system manager mode`"

### LINKED ISSUE #69: How to load "Specifie" service from bootloader/kernel comand line?
Hello.

 We can start the single service using dinit by entering `single` in the Bootloader command line.
But unfortunately, it is not possible to load another service with this method.
 This is important to me because I'm considering replacing the `single` service with `rescue` and also want to implement a systemd target-like structure in @Dinit-on-Devuan.
 This feature (calling any service using the Bootloader command line) makes it possible to run any target at system startup.

 @davmac314 Now my question is whether it is possible to do this or whether such a feature has been implemented or not?

regards

### PR DESCRIPTION
**Pull request by mobin-2008**
Hi!
This issue is discussed in #69 (although we need to talk more about it now). This time, I decided to add Add support for "Loading any service with dinit on system manager mode" with my c++ knowledge.

Fix #69

## Goal
Add support for loading a service at boot time. its good for create `rescue` service and boot it if necessary also its good for have SystemD target-like services.

## ToDo
- [x] Fix: We can Load a service with `dinit` in `user mode` but `dinit` restricts this feature to `single` service when run in `system manager mode`.
- ~~Pay attention to issue #74 and use `string_ha` instead of `string` if necessary (I have to look into it more).~~ **Its not necessary**
- [x] Modify Documention (in `dinit` man page) (https://github.com/davmac314/dinit/pull/76/commits/fa14434a5363f080a56b35270c05b4afb37ca4c8)
- [x] Add myself to `CONTRIBUTORS` (https://github.com/davmac314/dinit/pull/76/commits/5440558f312a8710dd072e02ab47c4b2da7b8b94)

`Signed-off-by: Mobin <mobin@mobintestserver.ir>`

### CODE REVIEW

**Comment by davmac314** [comment]
> Resolve conflict: The dinit --help says: <service-name> [...] start service with name <service-name>
but its not true! Its only work with single command.

You can specify any `<serivce-name>` if running dinit as a non-system instance. Relevant line is 388:
```
        if (!opts.process_sys_args || strcmp(argv[i], "single") == 0) {
            services_to_start.push_back(argv[i]);
        }
```
if `opts.process_sys_args` is not set, which is the case if pid != 1 or uid != 0, then any name (not just "single") will be treated as a service to start. Otherwise, only "single" is recognised.

**Comment by mobin-2008** [comment]
> > Resolve conflict: The dinit --help says:  [...] start service with name 
> > but its not true! Its only work with single command.
> 
> You can specify any `<serivce-name>` if running dinit as a non-system instance. Relevant line is 388:
> 
> ```
>         if (!opts.process_sys_args || strcmp(argv[i], "single") == 0) {
>             services_to_start.push_back(argv[i]);
>         }
> ```
> 
> if `opts.process_sys_args` is not set, which is the case if pid != 1 or uid != 0, then any name (not just "single") will be treated as a service to start. Otherwise, only "single" is recognised.

So it seems that you are not going to do this right now. no problem
I close this PR.

**Comment by davmac314** [comment]
I'm not sure if you understood me correctly. I was just pointing out that the current help is correct, if dinit is started as a user instance (or at least as a non-system-manager instance). The system-manager behaviour (where it only processes "single" and not other names) is documented in the man page for dinit.

I'd be quite happy to have this change made - and great if you can do it yourself! I'm happy to give whatever guidance/advice I can. Otherwise it will need to wait a little, and I will do it myself.

**Comment by mobin-2008** [comment]
Everything seems right. dinit compiles correctly. Now is the time to test. (Of course, there are still issues such as how to implement and document).

**Comment by davmac314** [comment]
I would suggest a few changes to what you have now:

- you shouldn't need the `specifie_service_loading`/`specifie_service_path` variables (lines 88-89)
- on line 329 and 330, instead of setting those variables, just add the service name directly to the `services_to_start` list at that time (eg `services_to_start.push_back(argv[i])`.
- line 364, please don't remove the original line from the help text as it is still valid to give a service name without prefixing it with `--service`.
- lines 402-404 shouldn't be needed

**Comment by mobin-2008** [comment]
> I would suggest a few changes to what you have now:
> 
>     * you shouldn't need the `specifie_service_loading`/`specifie_service_path` variables (lines 88-89)
> 
>     * on line 329 and 330, instead of setting those variables, just add the service name directly to the `services_to_start` list at that time (eg `services_to_start.push_back(argv[i])`.
> 
>     * line 364, please don't remove the original line from the help text as it is still valid to give a service name without prefixing it with `--service`.
> 
>     * lines 402-404 shouldn't be needed

Done! https://github.com/davmac314/dinit/pull/76/commits/afb3b88755b239912fe1c4443848219e750dd4dc

**Comment by mobin-2008** [comment]
Everything looks right. Now you can start a specific service instead of `boot` & `single` with the `--service` argument. It is also possible to start several services by adding several `--services`:
````
--service tty1 --service tty2
````

Only a few issues remain:
1- Isn't it better to have a distinction between `<service-name>` and `--service <service-name>` in `dinit --help`? It's a bit confusing now.
2- Isn't it better to have a shortcut for it (like `-t`) I myself suggest `-t`, it stands for target, which is similar to what we do with the `--service` argument

**Comment by davmac314** [comment]
> 1- Isn't it better to have a distinction between <service-name> and --service <service-name> in dinit --help? It's a bit confusing now.

I think it's ok as-is, I may amend before release. (It maybe just needs a very small explanation for when you should use `--service <name>` form instead of just `<name>`).

> 2- Isn't it better to have a shortcut for it (like -t) I myself suggest -t, it stands for target, which is similar to what we do with the --service argument

Yes, it would be fine to add that as a shortcut.

**Comment by mobin-2008** [comment]
> I think it's ok as-is, I may amend before release. (It maybe just needs a very small explanation for when you should use `--service <name>` form instead of just `<name>`).

Ok. be I'll leave it as is for now to check it out later.
> Yes, it would be fine to add that as a shortcut.

Ok. i working on it.

**Comment by mobin-2008** [comment]
Everything looks good. Its ready!

**Comment by davmac314** [comment]
Thanks! I'll tweak the wording of the documentation a bit, later, but looks good.

**Pull request merged**
