### PR TITLE
Website: Dinit's official website!

### PR DESCRIPTION
**Pull request by mobin-2008**
Hi! I working on Dinit's wiki but seems like github wiki is very harder to automate man-pages generator so I created all files needed to create official Dinit website on github-pages.

a live version is available [here](https://mobin-2008.github.io/dinit). I converted style of html files to plainest mode, I like it because I think it's enough for Dinit. but if you don't like it, I change that.

regards
## Goal
Official Dinit's website with auto man-page generator

## ToDo
- [x] Create workflow for deploy website
- [x] Create `index.html` (with minor changes from https://davmac.org/projects/dinit/index.html)

`Signed-off-by: Mobin "Hojjat" Aydinfar <mobin@mobintestserver.ir>`

### CODE REVIEW

**Comment by mobin-2008** [comment]
Usage: Go to repo settings, enable github-pages and use `github action` for page building, then merge this PR.

**Comment by davmac314** [comment]
Hey Mobin, I'd really like you to talk to me about things like this before starting work. I really don't want to deploy the website to github pages, and I don't need an automated update - the website is small and editing the HTML manually is perfectly reasonable and is currently my preferred way to make updates. (I know the man pages on the website are currently a little out-of-date, but I'll be more concerned about that once Dinit is ready for an official 1.0 release).

I feel bad that you've put effort into this and I won't use it, but you really should discuss with me first.

**Comment by mobin-2008** [comment]
@davmac314 No problem :) From now on I will discuss with you before working on new feature or something big!
Email is a good way, isn't?

**Comment by davmac314** [comment]
Yes, email is fine! Or open a discussion on github. Thanks :)

**Pull request closed without merging**
