### PR TITLE
Add always-chain option

### PR DESCRIPTION
**Pull request by asherikov**
`always-chain` alters behavior of `chains-to` property forcing the chained service to always start on termination of a service.

### CODE REVIEW

**Comment by davmac314** [comment]
Looks basically fine, I'm just curious about the use case for this (what is the option needed for)?

One minor quibble: the current code uniformly uses `||` and `!` rather than `or` and `not` keywords, please use the same convention.

Also, there is an integration test for `chain-to` (src/igr-tests/chain-to), please modify that test to also test this option, or add a new test.

**Comment by asherikov** [comment]
Fixed style, I'll add test a bit later.
The current goal is to be able to terminate all services and dinit if a particular service stops working for any reason. 
Can also be useful for sending notifications on service termination even if the service is automatically restarted.

**Comment by asherikov** [comment]
Added integration test. 

BTW, a higher level note -- `restart` and `chain-to` are related and can probably be generalized to something like this:
```
on-termination:
    reason: [success|failure|manual]
    service: <this or some other service>
    delay: X.X
    attempts: X
    ...
```

**Comment by davmac314** [comment]
It's true that they could be combined but the use cases are very different. I wouldn't want to have to repeat the service name in a restart directive. Also you can currently specify both restart options and a chain-to service, the latter will only get executed if the service won't restart (e.g if it failed too quickly and too many times); this would get awkward with a common syntax.

**Comment by davmac314** [comment]
(also: merged, thanks!)

**Pull request merged**
