### PR TITLE
CI & test suite!

### PR DESCRIPTION
**Pull request by mobin-2008**
CI must be able to:
1. Does the mconfig.Linux.sh script properly prepare the system for compilation? (`./configs/mconfig.Linux.sh`)
2. Can dinit be compiled? (`make`)
3. Does dinit work properly? (Unit & Integration tests) (`make check` & `make check-igr`)

# ToDo
- [ ] ~~Enable Integration tests on all test suites (Disabled due some bugs)~~ **Moved to another PR**
- [x] Debian (bullseye) - amd64 ci
- [x] Debian (bullseye) - i386 ci
- [x] Alpine Linux (latest) - armv8 ci

# Nice to have
- [x] Alpine Linux (latest) - armv7 ci
- [x] Alpine Linux (latest) - armv6 ci

I hope this merge request is helpful :)

### CODE REVIEW

**Comment by mobin-2008** [comment]
I decided to make ci better and use it later.

**Comment by mobin-2008** [comment]
> Regarding the MR, I guess having CI set up is a nice idea, but I think only a handful of targets are needed (it would be nice to have FreeBSD and OpenBSD, but they aren't available as targets if I understand correctly).

About BSDs, I cannot find a good image for FreeBSD or OpenBSD on docker hub. I will research more about it later
> Also the step you've called "Initial checks" should really be "Unit tests" and "Advanced checks" should be "Integration tests".

Done!  a8b4cab793ac2d28c58c9a071ce3d09ae581b283

**Comment by mobin-2008** [comment]
A new problem in debian-bullseye-aarch64. I do not know if the problem is with dinit or CI I have never tested dinit on an ARM based device.
github action log:

````  
...
make[3]: Leaving directory '/home/runner/work/dinit/dinit/src/tests/cptests'
  ./tests
  basic_test1...               PASSED
  basic_test2...               PASSED
  basic_test3...               PASSED
  basic_test4...               PASSED
  basic_test5...               PASSED
  basic_test6...               PASSED
  basic_test7...               PASSED
  basic_test8...               PASSED
  test_pin1...                 PASSED
  test_pin2...                 PASSED
  test_pin3...                 PASSED
  test_pin4...                 PASSED
  test_pin5...                 PASSED
  test_pin6...                 PASSED
  test_pin7...                 PASSED
  test_pin8...                 PASSED
  test_pin9...                 PASSED
  test_pin10...                PASSED
  test_softdep1...             PASSED
  test_softdep2...             PASSED
  test_softdep3...             PASSED
  test_softdep4...             PASSED
  test_softdep5...             PASSED
  test_softdep6...             PASSED
  test_softdep7...             PASSED
  test_softdep8...             PASSED
  test_other1...               PASSED
  test_other2...               PASSED
  test_other3...               PASSED
  test_other4...               PASSED
  test_other5...               PASSED
  test_other6...               PASSED
  test_log1...                 PASSED
  test_log2...                 PASSED
  ==4796==LeakSanitizer has encountered a fatal error.
  ==4796==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
  ==4796==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
  make[2]: *** [Makefile:12: run-tests] Error 1
  make[2]: Leaving directory '/home/runner/work/dinit/dinit/src/tests'
  make[1]: *** [Makefile:42: check] Error 2
  make[1]: Leaving directory '/home/runner/work/dinit/dinit/src'
  make: *** [Makefile:13: check] Error 2
  Error: The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2/src/run-on-arch.sh' failed with exit code 2
````

**Comment by davmac314** [comment]
> A new problem in debian-bullseye-aarch64. I do not know if the problem is with dinit or CI I have never tested dinit on an ARM based device.

Since this is your merge request, I'll leave it to you to debug it. (My suspicion is that it's an issue with leak sanitizer or a compiler bug).

**Comment by mobin-2008** [comment]
> > A new problem in debian-bullseye-aarch64. I do not know if the problem is with dinit or CI I have never tested dinit on an ARM based device.
> 
> Since this is your merge request, I'll leave it to you to debug it. (My suspicion is that it's an issue with leak sanitizer or a compiler bug).

I researched this, it looks like a bug in gcc.
https://bugzilla.redhat.com/show_bug.cgi?id=1950244
Unfortunately debian bullseye does not support gcc-11 or later and runs-on-arch does not support debian bookworm or sid.
So for now, I've replaced debian with alpine.

**Comment by mobin-2008** [comment]
> I researched this, it looks like a bug in gcc...

There seems to be a problem with the gcc-10 because my experiments with the gcc-11 in alpine had good results.
https://github.com/mobin-2008/dinit/runs/6894258855

**Comment by davmac314** [comment]
There are still too many targets for my taste... 3 or 4 would be good. More than that is just noise. Maybe make sure to have one target which uses musl instead of glibc (i.e. alpine), one ARM, one x86, one 32-bit, one 64-bit.

**Comment by mobin-2008** [comment]
I intend to move the goal of "Enable Integration tests on all test suites" to a separate PR.
My final list for ci is almost ready. Whenever this PR is ready, I take it out of Draft mode.
CI will eventually include these test suites:
Debian bullseye (stable) (glibc) amd64 & i386
Alpine linux (latest) (musl) armv8 (64-bit) & armv7 (32-bit) & armv6 (32-bit)

**Comment by mobin-2008** [comment]
Everything is ready!

**Pull request merged**
