### PR TITLE
meson: Some improvments to meson

### PR DESCRIPTION
**Pull request by mobin-2008**
Hi!
## Goal
Some fixes and improvements to Meson files
## ToDo
- [x] Pass non-string values for boolean options (Why `meson` doesn't warn about passing string values to boolean options?)
- [x] Split integration tests and unit tests with `suite` feature in [`test()`](https://mesonbuild.com/Reference-manual_functions.html#test) function
- [x] Make sure `-lrt` is supported by compiler/linker on FreeBSD
- [x] Some cleanups

Alpine CI: ✅ - https://builds.sr.ht/~mobin2008/job/941608
Debian CI: ✅ - https://builds.sr.ht/~mobin2008/job/941609
FreeBSD CI: ✅ - https://builds.sr.ht/~mobin2008/job/941610
OpenBSD CI: ✅ - https://builds.sr.ht/~mobin2008/job/941611

Regards

`Signed-off-by: Mobin Aydinfar <mobin@mobintestserver.ir>`

### CODE REVIEW

**Review by davmac314 — APPROVED** [review]

**Comment by davmac314** [comment]
I just tested the meson build and noticed there are a bunch of compiler warnings enabled that should not be enabled:
```
../src/includes/load-service.h:1207:16: warning: 'char* strncpy(char*, const char*, size_t)' specified bound 32 equals destination size [-Wstringop-truncation]
 1207 |         strncpy(settings.inittab_line, inittab_setting.c_str(), sizeof(settings.inittab_line));
      |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
../src/includes/service-listener.h:9:7: warning: 'class service_listener' has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
    9 | class service_listener
      |       ^~~~~~~~~~~~~~~~
```

Can we do something about this?

Also, running the tests (proctests, loadtests etc) doesn't show the output, so you can't see what tests are running and if any fails you can't see which one.

**Comment by mobin-2008** [comment]
> I just tested the meson build and noticed there are a bunch of compiler warnings enabled that should not be enabled:
> 
> ```
> ../src/includes/load-service.h:1207:16: warning: 'char* strncpy(char*, const char*, size_t)' specified bound 32 equals destination size [-Wstringop-truncation]
>  1207 |         strncpy(settings.inittab_line, inittab_setting.c_str(), sizeof(settings.inittab_line));
>       |         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> ```
> ../src/includes/service-listener.h:9:7: warning: 'class service_listener' has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
>     9 | class service_listener
>       |       ^~~~~~~~~~~~~~~~
> ```
> 
> Can we do something about this?

I think `warning_level=1` must pass less flags. I figure this out at tomorrow.

> Also, running the tests (proctests, loadtests etc) doesn't show the output, so you can't see what tests are running and if any fails you can't see which one.

Meson test runner by default don't print stdout/stderr from tests. All logs will be recorded in `builddir/meson-logs/testlog.txt`. Also you can use a flag to print output on failed tests in stdout. (Sorry I don't have access to my computer, you find it by `meson test --help`)

**Comment by davmac314** [comment]
> I think `warning_level=1` must pass less flags. I figure this out at tomorrow.

Ugh, this is bad. If we can't control which warnings are used we need to disable them altogether.

> Meson test runner by default don't print stdout/stderr from tests

Again, that's bad :(

**Comment by eli-schwartz** [comment]
`-Wnon-virtual-dtor` was removed from Meson's warning_level=1 in https://github.com/mesonbuild/meson/pull/10339 and that change was released in meson 1.0.0

**Comment by davmac314** [comment]
> usually the warning levels map essentially to "Wall, Wextra, Wpedantic, in order of warning level"

Is that documented?

Note that `-Wpedantic` isn't an a "level beyond" `-Wextra`, so I'm not sure that's a good scheme. Sometimes it's useful to have `-Wpedantic` alone without either of the other options, and that won't be the same as having all three.

**Comment by eli-schwartz** [comment]
Sure, and it's fine to manually `add_project_arguments('-Wpedantic', language: 'c')`. Meson won't warn you that you should use the builtin option (it will warn you if you add -Wall or -Wextra).

**Comment by davmac314** [comment]
@mobin-2008 are there any more deficiencies of the meson build compared to the makefile build that you're aware of? It would be good to get a handle on this and document any issues.

**Comment by davmac314** [comment]
> All logs will be recorded in builddir/meson-logs/testlog.txt

Unfortunately only cptests output is recorded there. The other test executables have their output swallowed, for some reason.

**Comment by mobin-2008** [comment]
> Again, that's bad :( I would have preferred that you had told me this when you submitted the PR for the meson build

I'm sorry. I didn't remember about that flag. it's `--print-errorlogs`. :(
> @mobin-2008 are there any more deficiencies of the meson build compared to the makefile build that you're aware of? It would be good to get a handle on this and document any issues.

Uhh, What do you mean by "deficiencies"? I don't understand.
> Unfortunately only cptests output is recorded there. The other test executables have their output swallowed, for some reason.

I are you sure about this? I test it and doesn't have any issues in recording stdout/err from tests. All unit tests stdouts are recorded.
Also in Meson 1.0, `warning_level=1` is more cleaner and just enable some flags.
```meson
$ meson compile
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja
[19/33] Compiling C++ object src/dinitctl.p/dinitctl.cc.o
In file included from ../src/dinitctl.cc:23:
In constructor ‘static_membuf<N>::static_membuf(char (&)[M], const T&) [with int M = 1; T = char; int N = 2]’,
    inlined from ‘static_membuf<(N + sizeof (U))> static_membuf<N>::append(const U&) [with U = char; int N = 1]’ at ../src/includes/dinit-client.h:91:49,
    inlined from ‘int add_remove_dependency(int, cpbuffer_t&, bool, const char*, const char*, dependency_type, bool)’ at ../src/dinitctl.cc:1326:20,
    inlined from ‘int dinitctl_main(int, char**)’ at ../src/dinitctl.cc:417:41:
../src/includes/dinit-client.h:84:15: warning: ‘dep_type’ may be used uninitialized [-Wmaybe-uninitialized]
   84 |         memcpy(buf + M, &val, sizeof(val));
      |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/dinitctl.cc: In function ‘int dinitctl_main(int, char**)’:
../src/dinitctl.cc:101:21: note: ‘dep_type’ was declared here
  101 |     dependency_type dep_type;
      |                     ^~~~~~~~
[33/33] Linking target src/halt

$
```

**Comment by davmac314** [comment]
> Uhh, What do you mean by "deficiencies"? I don't understand. All things are documented in `BUILD_MESON`.

I meant:
- individual test results are not shown
- some compiler warnings may be incorrectly enabled, resulting in warnings when building

Also, any way we can get it to use `-Os` instead of `-O3` for release builds? and enable `-flto`, if not by default at least as an option?

**Comment by davmac314** [comment]
> I are you sure about this? I test it and doesn't have any issues in recording stdout/err from tests

This is the entire log (minus the environment dump, which I redacted) after I run `ninja test` (or `meson test`):

```
Log of Meson test suite run on 2023-02-17T21:11:03.798846

Inherited environment: [redacted]

==================================== 1/5 =====================================
test:         tests
start time:   11:11:03
duration:     0.01s
result:       exit status 0
command:      MALLOC_PERTURB_=190 /home/davmac/workspace/dinit/msnbld/src/tests/tests
==============================================================================

==================================== 2/5 =====================================
test:         proctests
start time:   11:11:03
duration:     0.00s
result:       exit status 0
command:      MALLOC_PERTURB_=241 /home/davmac/workspace/dinit/msnbld/src/tests/proctests
==============================================================================

==================================== 3/5 =====================================
test:         loadtests
start time:   11:11:03
duration:     0.00s
result:       exit status 0
command:      MALLOC_PERTURB_=206 /home/davmac/workspace/dinit/msnbld/src/tests/loadtests
==============================================================================

==================================== 4/5 =====================================
test:         envtests
start time:   11:11:03
duration:     0.00s
result:       exit status 0
command:      MALLOC_PERTURB_=19 /home/davmac/workspace/dinit/msnbld/src/tests/envtests
==============================================================================

==================================== 5/5 =====================================
test:         cptests
start time:   11:11:03
duration:     0.00s
result:       exit status 0
command:      MALLOC_PERTURB_=37 /home/davmac/workspace/dinit/msnbld/src/tests/cptests/cptests
----------------------------------- stdout -----------------------------------
cptest_queryver...           PASSED
cptest_listservices...       PASSED
cptest_findservice1...       PASSED
cptest_findservice2...       PASSED
cptest_findservice3...       PASSED
cptest_loadservice...        PASSED
cptest_startstop...          PASSED
cptest_start_pinned...       PASSED
cptest_gentlestop...         PASSED
cptest_queryname...          PASSED
cptest_unload...             PASSED
cptest_addrmdeps...          PASSED
cptest_enableservice...      PASSED
cptest_restart...            PASSED
cptest_wake...               PASSED
cptest_servicestatus...      PASSED
==============================================================================


Ok:                 5   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
```

> Also in Meson 1.0, warning_level=1 is more cleaner and just enable some flags.

That's definitely better, but it's not documented so it's really unclear what `warning_level=1` is supposed to mean and whether it will continue to be what we want, but that's ok for now I guess.

**Comment by davmac314** [comment]
> Also, any way we can get it to use `-Os` instead of `-O3` for release builds?

I guess that should actually be done with a `minsize` build instead of a `release` build?

**Comment by mobin-2008** [comment]
> > Also, any way we can get it to use `-Os` instead of `-O3` for release builds?
> 
> I guess that should actually be done with a `minsize` build instead of a `release` build?

Why do you use `release` or `minsize` buildtypes? I set a `custom` buildtype with those settings:
https://github.com/davmac314/dinit/blob/8cbe235440ba0f14705e83b022e1788b32504fe7/meson.build#L10-L14

For `-flto` you can set `b_lto=true` (Seems like I need to mention some things from Meson docs in `BUILD_MESON`):
```sh
$ meson setup -Db_lto=true dirbuild
```

Regards

**Comment by mobin-2008** [comment]
> > I are you sure about this? I test it and doesn't have any issues in recording stdout/err from tests
> 
> This is the entire log (minus the environment dump, which I redacted) after I run `ninja test` (or `meson test`):
> 
> ```
> ...
> ```

Uhh, Seems like it's a meson bug. I didn't see something like this.
> > Also in Meson 1.0, warning_level=1 is more cleaner and just enable some flags.
> 
> That's definitely better, but it's not documented so it's really unclear what `warning_level=1` is supposed to mean and whether it will continue to be what we want, but that's ok for now I guess.

Yea, seems OK for now, Maybe I create a issue to request meson developers to document `warning_level` option.

**Comment by davmac314** [comment]
> Why do you use `release` or `minsize` buildtypes? I set a `custom` buildtype with those settings:

When I build, it uses `-O3` (can be seen by running `meson compile -v`). So that doesn't seem to work.

**Comment by davmac314** [comment]
I'm going to merge this now, but it would be great to improve the documentation at some point in the future:

- what the default build options are (-Os, no debug)
- how to do debug builds
- how to enable LTO
- how to see test logs

**Comment by davmac314** [comment]
One more thing: can you please properly squash your commits in pull requests from now on!

**Pull request merged**
