### PR TITLE
dinit monitor execute command for initial status

### PR DESCRIPTION
**Pull request by james-knippes**
I've refactored dinit-monitor a little bit to execute commands for the initial service state. Also added options to specify strings to be substituted per service state.

### CODE REVIEW

**Comment by davmac314** [comment]
Hey @james-knippes this is still set to draft, are you wanting review at this stage? From a quick look the only things I can point out are:

- Needs the man page for dinit-monitor to be updated
- I think it would be better from a user experience point-of-view to load all services specified first, then do the initial notification on each one. That way if one fails to load (wrong service name etc) you get an immediate error without getting notifications for the others.

**Comment by james-knippes** [comment]
Hey @davmac314,
yes thanks for the review. I've updated the man page and separated service loading and the initial status commands into two steps. Looks good now I think.

**Comment by davmac314** [comment]
I will look at this properly when I get a chance - may not be until the weekend.

**Comment by davmac314** [comment]
Hi @james-knippes , I pushed a commit with formatting fixes and some rewording. Please check it and see if you are happy with it. If so I'm happy to merge.

Unfortunately the commit is not showing in the github UI here in the PR, but it is visible on [your branch](https://github.com/james-knippes/dinit/tree/feature_dinit-monitor-initial-status). I can merge it manually if necessary.

**Comment by james-knippes** [comment]
Thanks @davmac314 , sounds way better now. Appreciate you also including explanations for the formatting changes/decisions in the commit. I happy with it.

Also for me the commit is not missing from the github UI. At least in this pr it is shown in the conversation/history for me.

**Comment by davmac314** [comment]
Seems there was just a delay in the UI showing the commit, it appears for me now too. Merged! Thanks.

**Pull request merged**
